### PR TITLE
Contributors image slider

### PR DESCRIPTION
**Pull request by 5thAttemptCode**
Changed the contributors section to be an image slider on mobile for better UX.

### CODE REVIEW

**Review by westerandr — CHANGES_REQUESTED** [review]
Good stuff uso! Just two change requests please:
1. If you could rebase your branch off the latest changes in main
2. Add yourself to the Contributors section 😄

**Comment by 5thAttemptCode** [comment]
Is up! :)

**Comment by 5thAttemptCode** [comment]
How could I not see this?? :D fixed it

**Review by westerandr — APPROVED** [review]
LGTM! Malo lava!

**Pull request merged**
